### ISSUE TITLE
Is right mouse down event disable?

### ISSUE THREAD

**Issue by Eragon-Brisingr** [ggerganov/imgui-ws#20]
When i try http://85.90.246.132:5001/ demo, go to "Popups & Modal Windows" -> "Context menus", right click button is not open popups windows. Have same way to fix it?

**Comment by Eragon-Brisingr** [comment]
When i debug imgui-ws, i find right mouse event in imgui-ws.js is 2, but imgui define this
> bool        MouseDown[5];                       // Mouse buttons: 0=left, 1=right, 2=middle + extras (ImGuiMouseButton_COUNT == 5). Dear ImGui mostly uses left and right buttons. Others buttons allows us to track if the mouse is being used by your application + available to user as a convenience via IsMouse** API.
I think this is the answer.

**Comment by ggerganov** [comment]
Thanks for spotting this - should be fixed now
