### ISSUE TITLE
Is compressor enable ?

### ISSUE THREAD

**Issue by Eragon-Brisingr** [ggerganov/imgui-ws#22]
I find compressor diff funtion cost large time, but it seem not use.

**Comment by ggerganov** [comment]
Can you clarify?

The compression is used here:
https://github.com/ggerganov/imgui-ws/blob/master/src/imgui-ws.cpp#L343-L351

**Comment by Eragon-Brisingr** [comment]
> Can you clarify?
> 
> The compression is used here: https://github.com/ggerganov/imgui-ws/blob/master/src/imgui-ws.cpp#L343-L351

But dataRead.drawListsDiff can not find any read reference. And i cancel calculate diff imgui-ws seem render right.

https://github.com/ggerganov/imgui-ws/blob/adece8ce24bfce7ed8ff77282c4c4e7f17b857a7/src/compressor-xor-rle-per-draw-list-with-vtx-offset.cpp#L94-L161

**Comment by Eragon-Brisingr** [comment]
![image](https://user-images.githubusercontent.com/16950908/167776411-7f9e9c09-ce25-4902-b062-cdab29c78443.png)

when draw many shape, Incppect::update cost too much time.

**Comment by ggerganov** [comment]
Probably, the compression is not efficient for your scene.

If it is possible, you can try to record your session and we can analyze the data to see what is the problem. To record a session, check the [record-sdl2](https://github.com/ggerganov/imgui-ws/tree/master/tools/record-sdl2) tool. Basically, you need to grab the `Session` class from [here](https://github.com/ggerganov/imgui-ws/blob/adece8ce24bfce7ed8ff77282c4c4e7f17b857a7/tools/common.h#L92) and use it to save your frames to a file. The file will be probably big, but if you could send it to me somehow, I can try to improve the compression algorithm to perform better in your case. You can also run the [compressor-benchmark](https://github.com/ggerganov/imgui-ws/tree/master/tools/compressor-benchmark) tool to get some information about the compression rate and performance for you scene.

**Comment by Eragon-Brisingr** [comment]
![ImGui_WS性能](https://user-images.githubusercontent.com/16950908/168409216-4c240367-cb5b-49b0-bf5d-6f94e6919011.png)
Maybe is stl debug too slow, I try unreal engine development settings, the performance is can accept.
